version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * 1,3,5,0"
    target-branch: "main"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    versioning-strategy: "increase"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    labels:
      - "dependencies"
    target-branch: "main"
    rebase-strategy: "auto"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
